/* ============================================================================
   PortfolioBlog - 테이블 생성 스크립트 (Oracle)
   ----------------------------------------------------------------------------
   실행 순서 : 03_drop_all.sql (재실행 시) -> 01_create_tables.sql -> 02_sample_data.sql

   [중요] VARCHAR2 길이에 CHAR 를 붙인 이유
     Oracle 은 기본이 BYTE 단위입니다. UTF-8 DB 에서 한글/일본어는 글자당 3바이트라
     VARCHAR2(100) 은 한글 33자밖에 안 들어가고 ORA-12899 가 납니다.
     VARCHAR2(100 CHAR) 로 쓰면 어떤 문자든 100'글자' 가 들어갑니다.

   [중요] 기본키는 IDENTITY 로 자동 증가합니다  (Oracle 12c 이상 / 21c 사용)
     GENERATED BY DEFAULT ON NULL AS IDENTITY
       - INSERT 할 때 id 칸을 아예 안 적으면 오라클이 번호를 넣어 줍니다.
       - NULL 을 넣어도 자동으로 채워집니다. (ON NULL 이 붙어서 그렇습니다)
       - 필요하면 값을 직접 넣을 수도 있습니다. 데이터 이관할 때 편합니다.
         GENERATED ALWAYS 로 하면 직접 넣는 것이 막혀 ORA-32795 가 납니다.

     속을 들여다보면 오라클이 시퀀스를 하나 자동으로 만들어 씁니다 (ISEQ$$_xxxxx).
     시퀀스가 사라진 것이 아니라, 오라클이 대신 만들어 관리해 주는 것입니다.
     테이블을 지우면 그 시퀀스도 같이 지워집니다.

     자바에서 방금 넣은 번호를 받으려면 컬럼 이름을 지정해야 합니다.
       PreparedStatement ps = con.prepareStatement(sql, new String[]{"POST_ID"});
       ... ps.executeUpdate();
       ResultSet rs = ps.getGeneratedKeys();   rs.next();   int id = rs.getInt(1);
   ============================================================================ */


/* ----------------------------------------------------------------------------
   1. blog_user : 관리자 계정 (글 쓰기 화면 로그인용)
   ---------------------------------------------------------------------------- */
CREATE TABLE blog_user (
    user_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    login_id    VARCHAR2(50 CHAR)   NOT NULL,
    password    VARCHAR2(200 CHAR)  NOT NULL,
    name        VARCHAR2(50 CHAR)   NOT NULL,
    email       VARCHAR2(100 CHAR),
    created_at  DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_blog_user      PRIMARY KEY (user_id),
    CONSTRAINT uq_blog_user_login UNIQUE (login_id)
);

COMMENT ON TABLE  blog_user          IS '관리자 계정';
COMMENT ON COLUMN blog_user.password IS '평문 저장 금지. 해시값을 저장할 것';


/* ----------------------------------------------------------------------------
   2. category : 글 분류 (기술 / 여행 / 일상)
                 채용담당자용 기술글과 개인 여행글을 나누는 기준이 됩니다.
   ---------------------------------------------------------------------------- */
CREATE TABLE category (
    category_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code        VARCHAR2(20 CHAR)   NOT NULL,
    name_ko     VARCHAR2(50 CHAR)   NOT NULL,
    name_ja     VARCHAR2(50 CHAR),
    sort_order  NUMBER(3)           DEFAULT 0 NOT NULL,
    CONSTRAINT pk_category      PRIMARY KEY (category_id),
    CONSTRAINT uq_category_code UNIQUE (code)
);

COMMENT ON TABLE  category      IS '글 분류 (기술 / 여행 / 일상)';
COMMENT ON COLUMN category.code    IS 'TECH / TRAVEL / DAILY';
COMMENT ON COLUMN category.name_ja IS '일본어 페이지에서 사용';


/* ----------------------------------------------------------------------------
   3. post : 블로그 글
   ---------------------------------------------------------------------------- */
CREATE TABLE post (
    post_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    category_id  NUMBER(10)         NOT NULL,
    title        VARCHAR2(200 CHAR) NOT NULL,
    slug         VARCHAR2(200 CHAR),
    summary      VARCHAR2(500 CHAR),
    content      CLOB               NOT NULL,
    thumbnail    VARCHAR2(300 CHAR),
    read_minutes NUMBER(3),
    status       VARCHAR2(10 CHAR)  DEFAULT 'DRAFT' NOT NULL,
    view_count   NUMBER(10)         DEFAULT 0 NOT NULL,
    created_at   DATE               DEFAULT SYSDATE NOT NULL,
    updated_at   DATE,
    published_at DATE,
    CONSTRAINT pk_post          PRIMARY KEY (post_id),
    CONSTRAINT uq_post_slug     UNIQUE (slug),
    CONSTRAINT fk_post_category FOREIGN KEY (category_id) REFERENCES category (category_id),
    CONSTRAINT ck_post_status   CHECK (status IN ('DRAFT', 'PUBLISHED'))
);

COMMENT ON TABLE  post          IS '블로그 글';
COMMENT ON COLUMN post.slug         IS 'URL 주소용 영문 식별자. 검색엔진 노출에 유리';
COMMENT ON COLUMN post.summary      IS '목록 화면에 보여줄 짧은 요약';
COMMENT ON COLUMN post.status       IS 'DRAFT(작성중) / PUBLISHED(공개)';
COMMENT ON COLUMN post.published_at IS '공개 전환 시각. 목록 정렬 기준';


/* ----------------------------------------------------------------------------
   4. tag : 태그 (글과 프로젝트가 함께 사용)
   ---------------------------------------------------------------------------- */
CREATE TABLE tag (
    tag_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name   VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT pk_tag      PRIMARY KEY (tag_id),
    CONSTRAINT uq_tag_name UNIQUE (name)
);

COMMENT ON TABLE  tag           IS '태그. 글과 프로젝트가 함께 사용한다';


/* ----------------------------------------------------------------------------
   5. post_tag : 글 <-> 태그 (N:M 을 풀어낸 연결 테이블)
                 글 하나에 태그 여러 개, 태그 하나에 글 여러 개가 붙습니다.
   ---------------------------------------------------------------------------- */
CREATE TABLE post_tag (
    post_id NUMBER(10) NOT NULL,
    tag_id  NUMBER(10) NOT NULL,
    CONSTRAINT pk_post_tag      PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_post_tag_post FOREIGN KEY (post_id) REFERENCES post (post_id) ON DELETE CASCADE,
    CONSTRAINT fk_post_tag_tag  FOREIGN KEY (tag_id)  REFERENCES tag  (tag_id)  ON DELETE CASCADE
);

COMMENT ON TABLE  post_tag      IS '글과 태그를 잇는 연결 테이블 (다대다)';


/* ----------------------------------------------------------------------------
   6. project : 포트폴리오 프로젝트
   ---------------------------------------------------------------------------- */
CREATE TABLE project (
    project_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title         VARCHAR2(200 CHAR)  NOT NULL,
    subtitle      VARCHAR2(200 CHAR),
    description   VARCHAR2(1000 CHAR),
    content       CLOB,
    category_code VARCHAR2(20 CHAR)   NOT NULL,
    thumbnail     VARCHAR2(300 CHAR),
    github_url    VARCHAR2(300 CHAR),
    demo_url      VARCHAR2(300 CHAR),
    team_size     NUMBER(3),
    my_role       VARCHAR2(200 CHAR),
    started_on    DATE,
    ended_on      DATE,
    is_featured   CHAR(1)             DEFAULT 'N' NOT NULL,
    sort_order    NUMBER(3)           DEFAULT 0 NOT NULL,
    created_at    DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_project             PRIMARY KEY (project_id),
    CONSTRAINT ck_project_category    CHECK (category_code IN ('WEB', 'DATA', 'MOBILE', 'ETC')),
    CONSTRAINT ck_project_featured    CHECK (is_featured IN ('Y', 'N')),
    CONSTRAINT ck_project_period      CHECK (ended_on IS NULL OR started_on IS NULL OR ended_on >= started_on)
);

COMMENT ON TABLE  project       IS '포트폴리오 작업물';
COMMENT ON COLUMN project.subtitle      IS '학과 팀 프로젝트 / 개인 사이드 프로젝트 등';
COMMENT ON COLUMN project.category_code IS 'projects.jsp 상단 필터와 연결되는 값';
COMMENT ON COLUMN project.content       IS '프로젝트 상세 회고. 채용담당자가 가장 눈여겨보는 부분';
COMMENT ON COLUMN project.my_role       IS '팀 프로젝트에서 본인이 맡은 역할';
COMMENT ON COLUMN project.is_featured   IS 'Y 면 홈 화면 최근 프로젝트에 노출';


/* ----------------------------------------------------------------------------
   7. project_tag : 프로젝트 <-> 태그 (사용 기술 스택)
   ---------------------------------------------------------------------------- */
CREATE TABLE project_tag (
    project_id NUMBER(10) NOT NULL,
    tag_id     NUMBER(10) NOT NULL,
    CONSTRAINT pk_project_tag         PRIMARY KEY (project_id, tag_id),
    CONSTRAINT fk_project_tag_project FOREIGN KEY (project_id) REFERENCES project (project_id) ON DELETE CASCADE,
    CONSTRAINT fk_project_tag_tag     FOREIGN KEY (tag_id)     REFERENCES tag     (tag_id)     ON DELETE CASCADE
);

COMMENT ON TABLE  project_tag   IS '작업물과 태그를 잇는 연결 테이블 (다대다)';


/* ----------------------------------------------------------------------------
   8. album : 여행 앨범
   ---------------------------------------------------------------------------- */
CREATE TABLE album (
    album_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title       VARCHAR2(200 CHAR)  NOT NULL,
    place       VARCHAR2(100 CHAR),
    country     VARCHAR2(50 CHAR),
    description VARCHAR2(1000 CHAR),
    travel_from DATE,
    travel_to   DATE,
    latitude    NUMBER(9, 6),
    longitude   NUMBER(9, 6),
    post_id     NUMBER(10),
    created_at  DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_album        PRIMARY KEY (album_id),
    CONSTRAINT fk_album_post   FOREIGN KEY (post_id) REFERENCES post (post_id) ON DELETE SET NULL,
    CONSTRAINT ck_album_period CHECK (travel_to IS NULL OR travel_from IS NULL OR travel_to >= travel_from)
);

COMMENT ON TABLE  album         IS '여행 앨범';
COMMENT ON COLUMN album.post_id   IS '이 여행에 대해 쓴 글이 있으면 연결. 없어도 됨';
COMMENT ON COLUMN album.latitude  IS '위도. 지도를 붙일 때 사용. 예) 34.669529';
COMMENT ON COLUMN album.longitude IS '경도. 예) 135.501651';


/* ----------------------------------------------------------------------------
   9. photo : 앨범 안의 사진
                대표 사진은 별도 테이블 대신 is_cover 플래그로 표시합니다.
                (album -> photo -> album 순환 외래키를 피하기 위함)
   ---------------------------------------------------------------------------- */
CREATE TABLE photo (
    photo_id   NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    album_id   NUMBER(10)         NOT NULL,
    file_name  VARCHAR2(300 CHAR) NOT NULL,
    caption    VARCHAR2(300 CHAR),
    taken_at   DATE,
    is_cover   CHAR(1)            DEFAULT 'N' NOT NULL,
    sort_order NUMBER(4)          DEFAULT 0 NOT NULL,
    CONSTRAINT pk_photo         PRIMARY KEY (photo_id),
    CONSTRAINT fk_photo_album   FOREIGN KEY (album_id) REFERENCES album (album_id) ON DELETE CASCADE,
    CONSTRAINT ck_photo_cover   CHECK (is_cover IN ('Y', 'N'))
);

COMMENT ON TABLE  photo         IS '앨범 안의 사진';
COMMENT ON COLUMN photo.file_name IS 'WebContent/images/ 아래 파일명';
COMMENT ON COLUMN photo.is_cover  IS '앨범 대표 사진 여부';


/* ----------------------------------------------------------------------------
   10. comment : 방문자 댓글
                 회원가입 없이 닉네임 + 비밀번호로 답니다 (티스토리 방식).
                 비밀번호는 댓글을 지울 때 본인 확인용입니다.
   ---------------------------------------------------------------------------- */
CREATE TABLE post_comment (
    comment_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    post_id    NUMBER(10)          NOT NULL,
    parent_id  NUMBER(10),
    nickname   VARCHAR2(30 CHAR)   NOT NULL,
    password   VARCHAR2(200 CHAR)  NOT NULL,
    content    VARCHAR2(1000 CHAR) NOT NULL,
    is_secret  CHAR(1)             DEFAULT 'N' NOT NULL,
    is_deleted CHAR(1)             DEFAULT 'N' NOT NULL,
    created_at DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_post_comment        PRIMARY KEY (comment_id),
    CONSTRAINT fk_comment_post        FOREIGN KEY (post_id)   REFERENCES post (post_id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_parent      FOREIGN KEY (parent_id) REFERENCES post_comment (comment_id),
    CONSTRAINT ck_comment_secret      CHECK (is_secret  IN ('Y', 'N')),
    CONSTRAINT ck_comment_deleted     CHECK (is_deleted IN ('Y', 'N'))
);

COMMENT ON TABLE  post_comment            IS '방문자 댓글';
COMMENT ON COLUMN post_comment.parent_id  IS '대댓글이면 부모 댓글 번호. 원댓글이면 NULL';
COMMENT ON COLUMN post_comment.password   IS '평문 저장 금지. 해시값을 저장할 것';
COMMENT ON COLUMN post_comment.is_secret  IS 'Y 면 비밀댓글 (작성자와 관리자만 열람)';
COMMENT ON COLUMN post_comment.is_deleted IS 'Y 면 삭제됨. 대댓글이 달려 있을 수 있어 실제로 지우지 않고 표시만 바꾼다';


/* ============================================================================
   인덱스 : 목록 조회에서 자주 쓰이는 정렬/조건 컬럼에 걸어둡니다.
            (기본키와 UNIQUE 제약은 인덱스가 자동 생성되므로 제외)
   ============================================================================ */

-- 공개된 글을 최신순으로 뽑는 목록 화면용
CREATE INDEX idx_post_status_pub ON post (status, published_at DESC);

-- 카테고리별 글 목록용
CREATE INDEX idx_post_category   ON post (category_id);

-- 연결 테이블을 태그 쪽에서 거슬러 찾을 때 (post_id 는 PK 앞자리라 인덱스가 이미 있음)
CREATE INDEX idx_post_tag_tag    ON post_tag (tag_id);
CREATE INDEX idx_project_tag_tag ON project_tag (tag_id);

-- 프로젝트 목록 정렬 및 필터용
CREATE INDEX idx_project_sort    ON project (sort_order, project_id);
CREATE INDEX idx_project_cat     ON project (category_code);

-- 앨범 안 사진을 순서대로 뽑을 때
CREATE INDEX idx_photo_album     ON photo (album_id, sort_order);

-- 글 하나의 댓글을 시간순으로 뽑을 때
CREATE INDEX idx_comment_post    ON post_comment (post_id, created_at);
CREATE INDEX idx_comment_parent  ON post_comment (parent_id);

COMMIT;
