/* ============================================================================
   PortfolioBlog - 시퀀스 방식 -> IDENTITY 방식으로 바꾸는 스크립트

   언제 쓰나
     예전 버전(기본키를 seq_post.NEXTVAL 로 직접 넣던 방식)으로 테이블을 이미
     만들어 두었고, 안에 든 데이터를 살리고 싶을 때 씁니다.

   테이블을 아직 안 만들었거나 지워도 되는 상태라면 이 파일은 필요 없습니다.
     03_drop_all.sql -> 01_create_tables.sql -> 02_sample_data.sql 로 하세요.

   무엇을 하나
     1. 기본키 컬럼 8개를 IDENTITY 로 바꿉니다.
        START WITH LIMIT VALUE 를 붙이면 지금 들어 있는 가장 큰 번호 다음부터
        시작합니다. 이걸 빼면 1번부터 시작해서 기본키가 겹칩니다.
     2. 더 이상 안 쓰는 시퀀스 8개를 지웁니다.

   [주의] 실행 전에 백업을 받아 두세요.
          ALTER TABLE 은 되돌리기 어렵습니다.
   ============================================================================ */


/* ------------------------------------------------- 1. 기본키를 IDENTITY 로 */
ALTER TABLE blog_user    MODIFY user_id    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE category     MODIFY category_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE post         MODIFY post_id    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE tag          MODIFY tag_id     GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE project      MODIFY project_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE album        MODIFY album_id   GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE photo        MODIFY photo_id   GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE post_comment MODIFY comment_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);

/* post_tag 와 project_tag 는 연결 테이블이라 자기 번호가 없습니다. 바꿀 것이 없습니다. */


/* ------------------------------------------------- 2. 안 쓰는 시퀀스 정리 */
DROP SEQUENCE seq_blog_user;
DROP SEQUENCE seq_category;
DROP SEQUENCE seq_post;
DROP SEQUENCE seq_tag;
DROP SEQUENCE seq_project;
DROP SEQUENCE seq_album;
DROP SEQUENCE seq_photo;
DROP SEQUENCE seq_comment;


/* ------------------------------------------------- 3. 확인용 */
/*
   IDENTITY 로 잘 바뀌었는지 봅니다. 8줄이 나오면 정상입니다.

   SELECT table_name, column_name, generation_type, identity_options
     FROM user_tab_identity_cols
    ORDER BY table_name;

   오라클이 대신 만들어 준 시퀀스도 볼 수 있습니다.

   SELECT sequence_name FROM user_sequences;
     -> ISEQ$$_71234 같은 이름이 8개 보이면 IDENTITY 가 쓰고 있는 것입니다.
        이건 직접 지우지 마세요. 테이블을 지울 때 같이 사라집니다.

   실제로 자동 증가하는지 넣어 봅니다.

   INSERT INTO tag (name) VALUES ('테스트');
   SELECT tag_id, name FROM tag WHERE name = '테스트';
   ROLLBACK;
*/

COMMIT;
